;PORTD'NIN 4. PÝNÝNE BAÐLI OLAN LEDÝ 1sn ARALIKLA
;YAKIP SÖNDÜRECEK ASSEMBLY KODUNU YAZINIZ.					
;____________________________________________________________________________________________________
DEFINITIONS:

	PTD	EQU 	$03
	DDRD	EQU	$07
	TBCR	EQU	$1C
	CONFIG1	EQU	$1F
	PCTL	EQU 	$36
	PBWC	EQU	$37	
	PMSH	EQU 	$38
	PMSL	EQU 	$39
	PMRS	EQU 	$3A
	PMDS	EQU	$3B

INITIALIZE:
	
	ORG	$8000
	
	MOV	#$31,CONFIG1	;CONFÝIG1 REGÝSTERINA ÝÞLEMCÝ ÝÇÝN GEREKLÝ AYARLAMA BÝLGÝSÝ YÜKLENDÝ.
	BCLR	5,PCTL		;PLL MODULU AYARLAMALAR ÝÇÝN DURDURULDU.
	
	MOV	#$00,PCTL	;PLL AYARI ÝÇÝN GEREKLÝ OLAN P SAYISI ÝÇÝN PRE1 VE PRE0 BÝTLERÝ '0' YAPILDI.
	MOV	#$01,PCTL	;PLL AYARI ÝÇÝN GEREKLÝ OLAN E SAYISI ÝÇÝN VPR0 '1' VE VPR1 '0' YAPILDI.
	
	MOV	#$01,PMSH	;PLL AYARI ÝÇÝN GEREKLÝ OLAN P SAYISI ÝÇÝN YÜKSEK ANLAMLI BYTE'A GEREKLÝ OLAN  01 DEÐERÝ YÜKLENDÝ.
	MOV	#$2C,PMSL	;PLL AYARI ÝÇÝN GEREKLÝ OLAN P SAYISI ÝÇÝN DÜÞÜK ANLAMLI BYTE'A GEREKLÝ OLAN 2C DEÐERÝ YÜKLENDÝ.
	
	MOV 	#$80,PMRS	;PLL AYARI ÝÇÝN GEREKLÝ OLAN L SAYISI DEÐERÝ YÜKLENDÝ.
	
	MOV	#$01,PMDS	;PLL AYARI ÝÇÝN GEREKLÝ OLAN R SAYISI DEÐERÝ YÜKLENDÝ.
	
	BSET 	5,PCTL		;PLL AYARI MODULU TEKRAR DEVREYE ALINDI.
	BSET	7,PBWC
	BRCLR	6,PBWC,*	;GEREKLÝ AYARLAMALAR TAMAMLANANA KADAR BURADA BEKLE.
	BSET	4,PCTL		;AYARLANAN VCO CLOCK'u ASIL KULLANILAN GERÇEK CLOCK OLARAK ÞEÇ.

MAIN:
	
	MOV	#$10,DDRD	;PTD'NÝN 4. PÝNÝNÝ ÇIKIÞ OLARAK TANIMLA.
	MOV	#$08,TBCR	;TBON=0 ÝLE TÝME-BASE KAPATLDI, TBR2=TBR1=TBR0=0 SEÇÝLEREK 1sn SEÇÝLDÝ.
				;TACK=1 ÝLE BAYRAK ÝNDÝRÝLDÝ. TBIE=0 YAPILARAK ÝNTERUPT VERMESÝ KAPATILDI.
	BSET 	2,TBCR		;TÝME-BASE TEKRARDAN ÝÞLEME BAÞLADI.

LABEL:
	BRCLR	7,TBCR,LABEL	;TBC'NIN 7 NOLU BÝTÝ '0' OLDUÐU MÜDDETÇE BURADA KAL.
	LDA	PTD		;PTD'DEKÝ ÝLGÝLERÝN HEPSÝNÝ AKUMULATÖRE KOY.
	EOR	#$FF		;AKUMULATÖRDEKÝ BÝLGÝ ÝLE FF DEÐERÝNÝ EXOR'LA VE SONUCU AKUMULATÖRE YAZ.
	STA	PTD		;AKUMULATÖR'DEKÝ BÝLGÝYÝ PTD'YE AKTAR.,
	BSET 	3,TBCR		;TÝME-BASE  MODULUNUN BAYRAÐINI ÝNDÝR.
	BRA	LABEL		;NE OLURSA OLSUN LABEL'A ATLA.
;____________________________________________________________________________________________________________
